---
title: "stl_lead_inequity"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(janitor)
```
Read in data and clean names 
```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv")) 

stl_lead <- stl_lead %>% janitor::clean_names()
```

Data summaries and visualizations
```{r}
dim(stl_lead)
skimr::skim(stl_lead)
names(stl_lead)
```

```{r}
stl_lead_prop <- stl_lead %>%
  mutate(prop_white = (white/ total_pop)*100)

dim(stl_lead_prop)
names(stl_lead_prop)
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = white)) +
  geom_jitter (aes(colour = pct_elevated))+
  scale_color_gradient(low = "navy", high = "red")+
  theme_minimal()+
  labs(title = "Percent children with elevated lead levels and percent white", 
       x = "Elevated lead",
       y = "Percent white")

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)
```
The higher the percentage of white individuals in a community is correlated with a lower percentage of children with elevated levels of lead in their blood.

```{r}
elevated_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated))+
  geom_histogram(fill = "Red", binwidth = 1)+ 
  labs(title = "Elevated lead levels")

elevated_lead_plot

ggsave(here::here("figs", "elevated_lead_plot.jpg"))
```

